import { StyleSheet } from 'react-native';
import colors from '../../../constants/colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.offWhiteBlueGray,
  },
  scrollContent: {
    padding: 24,
    paddingTop: 12,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    marginLeft: -4,
  },
  profileSection: {
    alignItems: 'center',
    marginBottom: 48,
  },
  avatarContainer: {
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: colors.lightCyanBlue,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
    borderWidth: 4,
    borderColor: colors.white,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    overflow: 'hidden',
  },
  avatar: {
    width: '100%',
    height: '100%',
  },
  name: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.charcoal,
    marginBottom: 4,
  },
  email: {
    fontSize: 16,
    color: colors.deepTeal,
    opacity: 0.6,
  },
  badgeContainer: {
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 6,
    backgroundColor: colors.transparentTeal05,
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: colors.transparentTeal01,
  },
  badgeText: {
    fontSize: 13.6,
    fontWeight: '600',
    color: colors.deepTeal,
    marginLeft: 8,
  },
  settingsContainer: {
    backgroundColor: colors.white,
    borderRadius: 16,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
    overflow: 'hidden',
    borderColor: colors.transparentTeal05,
    borderWidth: 1,
  },
  sectionHeader: {
    paddingHorizontal: 24,
    paddingVertical: 16,
    backgroundColor: colors.transparentTeal05,
  },
  sectionHeaderText: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    color: colors.mutedTeal,
  },
  settingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 24,
    backgroundColor: colors.white,
  },
  settingItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    paddingRight: 16,
  },
  settingIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: colors.lightSky, 
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 20,
  },
  settingItemTitle: {
    fontWeight: '700',
    color: colors.charcoal,
    fontSize: 16,
    marginBottom: 4,
  },
  settingItemSubtitle: {
    fontSize: 14,
    color: colors.deepTeal,
    opacity: 0.6,
  },
  divider: {
    height: 1,
    backgroundColor: colors.transparentTeal05,
  },
  logoutItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 24,
    backgroundColor: colors.white,
  },
  logoutIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: colors.red10, 
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 20,
  },
  logoutTitle: {
    fontWeight: '700',
    color: colors.red,
    fontSize: 16,
    marginBottom: 4,
  },
  logoutSubtitle: {
    fontSize: 14,
    color: colors.red,
    opacity: 0.6,
  },
  metaContainer: {
    marginTop: 48,
    alignItems: 'center',
  },
  versionText: {
    fontSize: 12,
    fontWeight: '500',
    color: colors.deepTeal,
    opacity: 0.4,
  },
  encryptedText: {
    fontSize: 11,
    color: colors.deepTeal,
    opacity: 0.3,
    marginTop: 6,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
});

export default styles;
